"""empty message

Revision ID: 114d9d050e36
Revises: 
Create Date: 2019-08-06 13:28:55.076997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114d9d050e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('DeptId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Deptname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('DeptId')
    )
    op.create_table('EvaluationQuestion',
    sa.Column('EvQId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CreatedDate', sa.String(length=100), nullable=True),
    sa.Column('EvQDescription', sa.String(length=100), nullable=True),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('EvQId')
    )
    op.create_table('EvaluationType',
    sa.Column('EvTId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvTName', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('EvTId')
    )
    op.create_table('Position',
    sa.Column('Pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Pid')
    )
    op.create_table('RegisterCompany',
    sa.Column('Regcom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Regcom_name', sa.String(length=100), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Phone', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('Admin_Username', sa.String(length=100), nullable=True),
    sa.Column('Admin_Password', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Regcom_id')
    )
    op.create_table('Usergroup',
    sa.Column('UserGroupID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UserGroupID')
    )
    op.create_table('evaluation',
    sa.Column('EvId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvDescription', sa.String(length=100), nullable=True),
    sa.Column('FromDate', sa.String(length=100), nullable=True),
    sa.Column('ToDate', sa.String(length=100), nullable=True),
    sa.Column('CreatedDate', sa.String(length=100), nullable=True),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('EvId')
    )
    op.create_table('EvalutaionQuestionDetail',
    sa.Column('EvQId', sa.Integer(), nullable=False),
    sa.Column('EvQDetailId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvQName', sa.String(length=100), nullable=True),
    sa.Column('MinScore', sa.Integer(), nullable=True),
    sa.Column('MaxScore', sa.Integer(), nullable=True),
    sa.Column('Answer', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['EvQId'], ['EvaluationQuestion.EvQId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('EvQId', 'EvQDetailId')
    )
    op.create_table('Office',
    sa.Column('OfficeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OfficeName', sa.String(length=255), nullable=True),
    sa.Column('DeptId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DeptId'], ['Department.DeptId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OfficeId')
    )
    op.create_table('User',
    sa.Column('UserId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Regcom_id', sa.Integer(), nullable=True),
    sa.Column('Username', sa.String(length=100), nullable=True),
    sa.Column('Password', sa.String(length=100), nullable=True),
    sa.Column('Created_date', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.Column('StaffId', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Regcom_id'], ['RegisterCompany.Regcom_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserId')
    )
    op.create_table('evaluation_detail',
    sa.Column('EvDId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvQId', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['EvQId'], ['EvaluationQuestion.EvQId'], ),
    sa.PrimaryKeyConstraint('EvDId', 'EvQId')
    )
    op.create_table('Staff',
    sa.Column('StaffId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SName', sa.String(length=100), nullable=True),
    sa.Column('Sex', sa.String(length=100), nullable=True),
    sa.Column('Dob', sa.String(length=100), nullable=True),
    sa.Column('Pob', sa.String(length=100), nullable=True),
    sa.Column('CurrentAddress', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DeptID', sa.Integer(), nullable=True),
    sa.Column('OfficeId', sa.Integer(), nullable=True),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('UserGroupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DeptID'], ['Department.DeptId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OfficeId'], ['Office.OfficeId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Pid'], ['Position.Pid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserGroupID'], ['Usergroup.UserGroupID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StaffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Staff')
    op.drop_table('evaluation_detail')
    op.drop_table('User')
    op.drop_table('Office')
    op.drop_table('EvalutaionQuestionDetail')
    op.drop_table('evaluation')
    op.drop_table('Usergroup')
    op.drop_table('RegisterCompany')
    op.drop_table('Position')
    op.drop_table('EvaluationType')
    op.drop_table('EvaluationQuestion')
    op.drop_table('Department')
    # ### end Alembic commands ###
