"""empty message

Revision ID: 204db5157dc7
Revises: 
Create Date: 2019-07-25 15:09:04.406076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204db5157dc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('DeptId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Deptname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('DeptId')
    )
    op.create_table('Position',
    sa.Column('Pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Pname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Pid')
    )
    op.create_table('Usergroup',
    sa.Column('UserGroupID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('UserGroupID')
    )
    op.create_table('Office',
    sa.Column('OfficeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OfficeName', sa.String(length=255), nullable=True),
    sa.Column('DeptId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DeptId'], ['Department.DeptId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('OfficeId')
    )
    op.create_table('Staff',
    sa.Column('StaffId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SName', sa.String(length=100), nullable=True),
    sa.Column('Sex', sa.String(length=100), nullable=True),
    sa.Column('Dob', sa.String(length=100), nullable=True),
    sa.Column('Pob', sa.String(length=100), nullable=True),
    sa.Column('CurrentAddress', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DeptID', sa.Integer(), nullable=True),
    sa.Column('OfficeId', sa.Integer(), nullable=True),
    sa.Column('Pid', sa.Integer(), nullable=True),
    sa.Column('CreatedBy', sa.String(length=100), nullable=True),
    sa.Column('UserGroupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DeptID'], ['Department.DeptId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['OfficeId'], ['Office.OfficeId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Pid'], ['Position.Pid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserGroupID'], ['Usergroup.UserGroupID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('StaffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Staff')
    op.drop_table('Office')
    op.drop_table('Usergroup')
    op.drop_table('Position')
    op.drop_table('Department')
    # ### end Alembic commands ###
