"""empty message

Revision ID: 304d0e5bdbe3
Revises: fd252b4c134d
Create Date: 2019-07-23 17:39:12.375324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304d0e5bdbe3'
down_revision = 'fd252b4c134d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Office', sa.Column('DeptId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Office', 'Department', ['DeptId'], ['DeptId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Office', type_='foreignkey')
    op.drop_column('Office', 'DeptId')
    # ### end Alembic commands ###
