"""empty message

Revision ID: 839ad9e4bd31
Revises: 114d9d050e36
Create Date: 2019-08-06 13:30:40.204187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839ad9e4bd31'
down_revision = '114d9d050e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Evaluation',
    sa.Column('EvId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EvDescription', sa.String(length=100), nullable=True),
    sa.Column('FromDate', sa.String(length=100), nullable=True),
    sa.Column('ToDate', sa.String(length=100), nullable=True),
    sa.Column('CreatedDate', sa.String(length=100), nullable=True),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('EvId')
    )
    op.create_table('EvaluationDetail',
    sa.Column('EvId', sa.Integer(), nullable=False),
    sa.Column('EvQId', sa.Integer(), nullable=False),
    sa.Column('CreatedDate', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['EvId'], ['Evaluation.EvId'], ),
    sa.ForeignKeyConstraint(['EvQId'], ['EvaluationQuestion.EvQId'], ),
    sa.PrimaryKeyConstraint('EvId', 'EvQId')
    )
    op.drop_table('evaluation')
    op.drop_table('evaluation_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_detail',
    sa.Column('EvDId', sa.INTEGER(), server_default=sa.text('nextval(\'"evaluation_detail_EvDId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('EvQId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CreatedDate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['EvQId'], ['EvaluationQuestion.EvQId'], name='evaluation_detail_EvQId_fkey'),
    sa.PrimaryKeyConstraint('EvDId', 'EvQId', name='evaluation_detail_pkey')
    )
    op.create_table('evaluation',
    sa.Column('EvId', sa.INTEGER(), server_default=sa.text('nextval(\'"evaluation_EvId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('EvDescription', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('FromDate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ToDate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('CreatedDate', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('StaffId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('EvId', name='evaluation_pkey')
    )
    op.drop_table('EvaluationDetail')
    op.drop_table('Evaluation')
    # ### end Alembic commands ###
