"""empty message

Revision ID: 8e1fc21f809e
Revises: 
Create Date: 2019-07-22 15:57:29.070607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1fc21f809e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('DeptId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Deptname', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('DeptId')
    )
    op.create_table('Office',
    sa.Column('OfficeId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('OfficeName', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('OfficeId')
    )
    op.create_table('Staff',
    sa.Column('StaffId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SName', sa.String(length=100), nullable=True),
    sa.Column('Sex', sa.String(length=100), nullable=True),
    sa.Column('Dob', sa.Date(), nullable=True),
    sa.Column('Pob', sa.String(length=100), nullable=True),
    sa.Column('CurrrentAddress', sa.String(length=255), nullable=True),
    sa.Column('Phone', sa.String(length=100), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DeptID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DeptID'], ['Department.DeptId'], ),
    sa.PrimaryKeyConstraint('StaffId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Staff')
    op.drop_table('Office')
    op.drop_table('Department')
    # ### end Alembic commands ###
