"""empty message

Revision ID: cf4e77fcffe6
Revises: 839ad9e4bd31
Create Date: 2019-08-06 14:20:48.150863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4e77fcffe6'
down_revision = '839ad9e4bd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssignStaff',
    sa.Column('Aid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fromDate', sa.String(length=100), nullable=True),
    sa.Column('toDate', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.Column('Description', sa.String(length=100), nullable=True),
    sa.Column('EvID', sa.Integer(), nullable=False),
    sa.Column('StaffId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EvID'], ['Evaluation.EvId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['StaffId'], ['Staff.StaffId'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('Aid', 'EvID')
    )
    op.add_column('Evaluation', sa.Column('EvTId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Evaluation', 'EvaluationType', ['EvTId'], ['EvTId'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('EvaluationDetail_EvId_fkey', 'EvaluationDetail', type_='foreignkey')
    op.create_foreign_key(None, 'EvaluationDetail', 'Evaluation', ['EvId'], ['EvId'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EvaluationDetail', type_='foreignkey')
    op.create_foreign_key('EvaluationDetail_EvId_fkey', 'EvaluationDetail', 'Evaluation', ['EvId'], ['EvId'])
    op.drop_constraint(None, 'Evaluation', type_='foreignkey')
    op.drop_column('Evaluation', 'EvTId')
    op.drop_table('AssignStaff')
    # ### end Alembic commands ###
