"""empty message

Revision ID: fd252b4c134d
Revises: 8e1fc21f809e
Create Date: 2019-07-23 11:28:30.880616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd252b4c134d'
down_revision = '8e1fc21f809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Staff', sa.Column('OfficeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Staff', 'Office', ['OfficeId'], ['OfficeId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Staff', type_='foreignkey')
    op.drop_column('Staff', 'OfficeId')
    # ### end Alembic commands ###
